prompt --install_component
@@application/set_environment.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/app_133410_logo_png.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/plugins/template_component/theme_42_content_row.sql
@@application/shared_components/plugins/template_component/theme_42_media_list.sql
@@application/shared_components/plugins/template_component/theme_42_timeline.sql
@@application/pages/delete_00000.sql
@@application/pages/page_00000.sql
@@application/pages/delete_00001.sql
@@application/pages/page_00001.sql
@@application/pages/delete_00002.sql
@@application/pages/page_00002.sql
@@application/pages/delete_00005.sql
@@application/pages/page_00005.sql
@@application/pages/delete_00007.sql
@@application/pages/page_00007.sql
@@application/pages/delete_00011.sql
@@application/pages/page_00011.sql
@@application/pages/delete_00013.sql
@@application/pages/page_00013.sql
@@application/pages/delete_09999.sql
@@application/pages/page_09999.sql
@@application/end_environment.sql
